### ISSUE TITLE
Error in Spark Operator Test

### ISSUE THREAD

**Issue by regaleo605** [apache/incubator-wayang#138]
I tried running this [class](https://github.com/apache/incubator-wayang/blob/main/wayang-platforms/wayang-spark/code/test/java/org/apache/wayang/spark/operators/SparkCartesianOperatorTest.java) in my Intellij. However I got the following error;

Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
22/04/07 11:31:38 WARN Utils: Your hostname, xxx resolves to a loopback address: 127.0.1.1; using 10.x.x.1 instead (on interface wlo1)
22/04/07 11:31:38 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address

java.lang.ExceptionInInitializerError

I think it is a local machine problem in my side. If so, do we need to also add documentation for people trying to use Spark?

**Comment by regaleo605** [comment]
Sorry,

So I just need to open the terminal of the project and just type EXPORT SPARK_LOCAL_IP=MY_IP in the command line?

**Comment by 2pk03** [comment]
Yes, in a terminal or via export variables in your IDE. That should to the trick :)

**Comment by 2pk03** [comment]
Yes, I wrote a small blog post about:
https://mapredit.blogspot.com/2021/09/compile-apache-wayang-on-mac-m1.html

For OSX it's easy with brew

**Comment by berttty** [comment]
@regaleo605 
Did you solve it?

**Comment by regaleo605** [comment]
More or less, so if you don't install Spark then you can't use the command export SPARK_LOCAL_IP in the terminal.

I assume that is also the case with sqlite and maybe other wayang platform?

Thank you in advance

**Comment by 2pk03** [comment]
Yes, you need to have access to the platforms to use Wayang. Wayang is a sublayer above the processing frameworks you want to use: wayang.apache.org/documentation 
https://github.com/databloom-ai/BDE is a full prebuilt dev environment, comes also as docker container.

**Comment by regaleo605** [comment]
No wonder, then issues solved. Thank you for the clarification. It was helpful
