### ISSUE TITLE
Smooth-Installation

### ISSUE THREAD

**Issue by JorgeQuiane** [apache/incubator-wayang#282]
We need to improve the installation of wayang so that most people (including non-experts) can install and get jobs running on Wayang. For this we need to be able to:
- make sure the readme instructions are correct and correct them if necessary (https://github.com/apache/incubator-wayang)
- give a pointer to these instructions in the Wayang website (https://wayang.apache.org/documentation/)
- improve the installation process so that it gets super simple to do by non-experts
- test all the benchmarks (https://github.com/apache/incubator-wayang/tree/main/wayang-benchmark) and write the instructions to run such benchmarks (this will be like the test of the Wayang installation)

**Comment by zkaoudi** [comment]
Just to make things more concrete: We need to separate between two things: 

1. Running Wayang after building it with maven.
- Improve instructions for building, if necessary
- Include scripts or instructions on how to execute an example and the benchmark tasks

2. Running Wayang after downloading the file from the downloads page. Current problems with this are:
- there is no wayang-submit script, in contrast to what is written in the README
- The file from the download page is a zip and the command indicated in the README assumes a .gz file
- The file linked in the download page is a source release. Is there somewhere a file with binaries only? If yes, we should point to that one. If not, we should create one.

**Comment by bgeng777** [comment]
Hi there, thanks for creating this issue. I am new to wayang and when I tried to follow the current README to run the wordcount example, I met the problem that there is no wayang-submit script. 
I finally managed to run the example with wayang-submit and the process is as follows:
#### 1. Get the wayang-submit binary
As @zkaoudi mentioned, there is no wayang-submit binary file in the downloaded zip file. To get the binary, I build the main branch of the repo with `./mvnw clean install -DskipTests  ` and finally get the jar in the repo's `bin` folder:
![image](https://user-images.githubusercontent.com/80749729/231810865-45ab3141-5558-4d8e-8d74-ddea3b1c21a4.png)
#### 2. Copy the binary to extracted apache-wayang-0.6.0-incubating folder and relevant jars for the WordCount example
After copying wayang-submit to extracted apache-wayang-0.6.0-incubating folder, I tried to run command like `wayang-submit org.apache.wayang.apps.wordcount.Main java file://$(pwd)/README.md`, but I met many errors about class missing. 
After some debugging, I make dir named 'jars' under WAYANG_HOME (it looks like Wayang will add jars under WAYANG_HOME/jars into the classpath) and copied following jars from the project repo into it(these jars should be built or downloaded by maven after building the project).
![image](https://user-images.githubusercontent.com/80749729/231811530-0afcb611-ed00-43a1-81a6-89be1a60ed1e.png)
#### 3. Run `wayang-submit` with WordCount example
After step 1 and 2, I can run:
```
wayang-submit org.apache.wayang.apps.wordcount.Main java file://$(pwd)/README.md
```
and get the output:
![image](https://user-images.githubusercontent.com/80749729/231813486-ee7eedf0-6d5e-4c17-bde1-91354c9ee509.png)


So according to my experience, I believe there are at least 2 more things we may need to take care:
1. Add necessary jars into the released package
2. Avoid printing some meaningless info in the terminal like:
![image](https://user-images.githubusercontent.com/80749729/231814329-0c177e54-f896-4539-a46a-3ef93823a714.png)
3. We may need to get rid of `aws-java-sdk-bundle-1.11.271.jar` dependency when running locally.

I hope my experience can help others who just want to give a try on the quickstart and I am willing to help to make this process more smooth and user-friendly.

**Comment by zkaoudi** [comment]
That is great. Just a question:
At which point you get all this meaningless info in the terminal? When running in the WordCount?

**Comment by bgeng777** [comment]
@zkaoudi You are right that the "meaningless" info(maybe jars under some classpath) is printed after I type command like `wayang-submit org.apache.wayang.apps.wordcount.Main java file://$(pwd)/README.md`. Also, I can see some output that alerts me that there are no jars/lib directories under WAYANG_HOME. I have not gave a deep look at the source code and am not so sure if they are relevant.

**Comment by zkaoudi** [comment]
I believe this issue has now been addressed. Thanks @bgeng777!
