### ISSUE TITLE
hard-coded path

### ISSUE THREAD

**Issue by zkaoudi** [apache/incubator-wayang#305]
The WayangTableScanVisitor class contain a hard-coded path 
https://github.com/apache/incubator-wayang/blob/main/wayang-api/wayang-api-sql/src/main/java/org/apache/wayang/api/sql/calcite/converter/WayangTableScanVisitor.java#L61

@kbeedkar could you please take a look at this?

**Comment by kbeedkar** [comment]
I am on it.

**Comment by kbeedkar** [comment]
this issue can be closed.
