### ISSUE TITLE
SqlContext has no option to configure platforms

### ISSUE THREAD

**Issue by juripetersen** [apache/incubator-wayang#378]
The SqlContext's constructor hard-codes three platforms and provides no options to customise the desired plugins and therefore used platforms:

```java
public SqlContext(Configuration configuration) throws SQLException {
        Configuration configuration1 = configuration.fork(String.format("SqlContext(%s)", configuration.getName()));

        wayangContext = new WayangContext(configuration1)
                .withPlugin(Java.basicPlugin())
                .withPlugin(Spark.basicPlugin())
                .withPlugin(Postgres.plugin());

        calciteSchema = SchemaUtils.getSchema(configuration);
    }
```

A proposed solution would be to change `SqlContext` so that it extends `WayangContext`, providing the desired functionality.

**Comment by kbeedkar** [comment]
@juripetersen Indeed. Can you go ahead with your proposed solution and create a PR?

**Comment by juripetersen** [comment]
@kbeedkar the PR is now linked.
