### ISSUE TITLE
New plugin which replaces postgres plugin and can add any jdbc platform.

### ISSUE THREAD

**Issue by Vigneshwar2002** [apache/incubator-wayang#380]
The current wayang architecture becomes tedious when we want to add a new JDBC platforms. one can see from postgres and sqlite3 modules that there is a lot of code redundancy.

So we can write a new plugin that can add any jdbc plaform by simply taking the corresponding jdbc driver through configuration.

we can change the API usage as below.
`WayangContext wayangContext = new WayangContext(configuration)
                .withPlugin(Java.basicPlugin())
                .withPlugin(GenericJdbc.plugin())
                ;`
` configuration.setProperty("wayang.postgres.jdbc.driverName", "org.postgresql.Driver");`
` TableSource person = new GenericJdbcTableSource("postgres","person");
`

User has to provide the name of the jdbc platform on which his table resides.

**Comment by kbeedkar** [comment]
To be clear, it does not replace the existing PostgresSql platform, but adds a new plugin, that allows
- support different jdbc platforms
- multiple instances of the same DBMS

**Comment by 2pk03** [comment]
Thank you, I checked and would +1 on this!
