### ISSUE TITLE
Jdbc and Postgres do not support JoinOperators yet

### ISSUE THREAD

**Issue by juripetersen** [apache/incubator-wayang#384]
The Postgres Platform only supports simple select-project queries for now.
Introducing Joins would expand the possibilities of using Postgres with Wayang.

I will open a pull request and propose a solution to this.

**Comment by kbeedkar** [comment]
At the moment only simple projections and filters can be pushed down. Supporting join push downs is welcomed.

**Comment by zkaoudi** [comment]
+1
