### ISSUE TITLE
How much faster is Apache Wayang than other frameworks? 

### ISSUE THREAD

**Issue by section9-lab** [apache/incubator-wayang#390]
How much faster is Apache Wayang than other frameworks?

Is there a Benchmark data comparison chart?

**Comment by 2pk03** [comment]
We did some, here's a blogpost about: https://www.blossomsky.io/blog/benchmarking-datablooms-blossom-achieving-faster-and-more-efficient-big-data-analytics

**Comment by 2pk03** [comment]
We updated the website, here's the benchmark:
https://wayang.apache.org/docs/introduction/benchmark
