### ISSUE TITLE
[Question] How to print/explain plans?

### ISSUE THREAD

**Issue by wangxiaoying** [apache/incubator-wayang#417]
Is there a way to explain (print out) the logical and physical plan for wayang?

**Comment by kbeedkar** [comment]
A quick and dirty solution as a workaround:  https://github.com/apache/incubator-wayang/blob/b134ec4a8b8038486025b47091920d1a85d3f298/wayang-api/wayang-api-sql/src/test/java/org/apache/wayang/api/sql/SqlToWayangRelTest.java#L109

**Comment by zkaoudi** [comment]
Besides that @juripetersen is currently implementing an explain() functionality in the plan builder that will print the logical, inflated, and physical plans. It should be ready soon :)

**Comment by zkaoudi** [comment]
Hi @wangxiaoying,

I assume you saw the last merged commit adding the explain functionality. Let us know if you have any further questions. More than happy to help out.

**Comment by wangxiaoying** [comment]
> Hi @wangxiaoying,
> 
> I assume you saw the last merged commit adding the explain functionality. Let us know if you have any further questions. More than happy to help out.

Thank you, I will definitely try!
